fix(core): abort execution of cx on unsupported systems (CLX-3277)

diff --git a/cx b/cx
--- a/cx
+++ b/cx
@@ -26,7 +26,27 @@ function get_host_os_type {
             echo "UNKNOWN"
     esac
 }
+
+# detect host OS
 HOST_OS=$(get_host_os_type)
+
+# perform host OS specific initialization
+case "$HOST_OS" in
+    Darwin)
+        # detect group of docker socket
+        GROUP_OF_SOCKET=$(stat -f '%g' /var/run/docker.sock)
+        ;;
+
+    Linux)
+        # detect group of docker socket
+        GROUP_OF_SOCKET=$(stat -c '%g' /var/run/docker.sock)
+        ;;
+
+    *)
+        echo "Your system ($HOST_OS) is not supported. Abort..."
+        exit 1
+        ;;
+esac
 
 # Wrapper for bash 3
 if [[ "${BASH_VERSION:0:1}" -lt 4 || "$@" == "env shell --wrapper" ]]; then
@@ -35,18 +55,6 @@ if [[ "${BASH_VERSION:0:1}" -lt 4 || "$@" == "env shell --wrapper" ]]; then
     if [[ "$@" == "env shell --wrapper" ]]; then
         command="cd /root && bash"
     fi
-
-    # detect group of docker socket
-    case "$HOST_OS" in
-        Darwin)
-            GROUP_OF_SOCKET=$(stat -f '%g' /var/run/docker.sock)
-            ;;
-
-        #Linux
-        *)
-            GROUP_OF_SOCKET=$(stat -c '%g' /var/run/docker.sock)
-            ;;
-    esac
 
     # Pass everything through our wrapper
     docker run --rm -ti --name clx-win-wrapper --user=$(id -u):$GROUP_OF_SOCKET -v "$(pwd -P)/":/root -v /var/run/docker.sock:/var/run/docker.sock cloudrexx/ubuntu bash -c "$command"
